site_name: HTB Cheatsheets
site_url: https://example.com
repo_url: https://github.com/example/htb-cheats
use_directory_urls: true
theme:
  name: material
  language: en
  font:
    text: Inter
    code: JetBrains Mono
  palette:
  - scheme: slate
    primary: blue grey
    accent: cyan
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  - scheme: default
    primary: grey
    accent: emerald
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  features:
  - navigation.tabs
  - navigation.sections
  - search.highlight
  - search.suggest
  - content.tabs.link
  - content.code.copy
extra_css:
- overrides/assets/styles.css
extra_javascript:
- overrides/assets/app.js
plugins:
- search
- macros
- git-revision-date-localized:
    fallback_to_build_date: true
- glightbox
markdown_extensions:
- admonition
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight
- pymdownx.inlinehilite
- toc:
    permalink: true
extra:
  target_ip: 10.10.10.10
  domain: example.htb
nav:
- Home: index.md
- Active Directory:
  - Kerberoasting: Active_Directory/kerberoasting.md
- Privesc:
  - Windows Privilege Escalation: Privesc/windows_privesc.md
- Web:
  - SQL Injection: Web/sql_injection.md
